#!/bin/bash

curl -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/download/v1.0.1/manifest-tool-linux-amd64
chmod +x manifest-tool

# manifest push fails if other arch tags are not there yet (ie build is still running)
./manifest-tool push from-spec multi-arch-manifest.yaml || true
